#!/bin/zsh
# This script builds the documentation

MATLAB='/Applications/MATLAB_R2010a.app/bin/matlab'
if [ -f $MATLAB ]; then
	$MATLAB -nodesktop -nosplash -maci -r "publish('runtest.m');pause(2);exit"
fi

# We scrape the version number from the main opticka file
VER=$(grep -o -E -e "version='[0-9\.]+'" opticka.m | grep -o -E -e "[0-9\.]+")
echo; echo "Opticka version = $VAR"
# and then edit the Doxygen file
sed -i "s/^\(PROJECT_NUMBER\)[ ]*=.*/\1 = $VER/g" .doxyfile
echo; echo "Edited .doxyfile"

doxygen .doxyfile
echo; echo "Ran doxygen"
open html/index.html
open html/runtest.html
echo; echo "FINISHED!"
rm .doxyfilee
rm debug.txt
exit 0
