#!/bin/zsh
# This script builds the documentation

MATLAB='/Applications/MATLAB_R2012a.app/bin/matlab'
if [ -f $MATLAB ]; then
	$MATLAB -nodesktop -nosplash -r "publish('runtest.m');pause(2);exit"
fi

# We scrape the version number from the main opticka file
VER=$(grep -o -E -e "optickaVersion='[0-9\.]+'" opticka.m | grep -o -E -e "[0-9\.]+")
echo; echo "---> Opticka version = $VER"; echo
sleep 1
# and then edit the Doxygen file
sed -i -e "s/^\(PROJECT_NUMBER\)[ ]*=.*/\1 = $VER/g" .doxyfile
if [ $? -eq 0 ]; then
	echo; echo "---> Edited .doxyfile"; echo
else
	echo; echo "---> Edit .doxyfile FAILED"; echo
fi
sleep 2
echo; echo "---> Will run DOXYGEN"; echo
doxygen .doxyfile
echo; echo "---> Ran doxygen"
open html/index.html
open html/runtest.html
echo; echo "---> FINISHED!"
rm .doxyfilee
rm .doxyfile-e
rm debug.txt
exit 0
